name: notification_flutter_poc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  awesome_notifications: ^0.10.1
  awesome_notifications_core: ^0.10.0 
  awesome_notifications_fcm: ^0.10.0 
  firebase_core: ^3.15.1
  firebase_crashlytics: ^4.3.9
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
